export const categories = [
  { id: '1', name: 'Temple', icon: '🛕', color: '#FF6B6B' },
  { id: '2', name: 'Hill Station', icon: '🏔️', color: '#4ECDC4' },
  { id: '3', name: 'Beach', icon: '🏖️', color: '#45B7D1' },
  { id: '4', name: 'Heritage', icon: '🏛️', color: '#96CEB4' },
  { id: '5', name: 'Wildlife', icon: '🦁', color: '#B980F0' },
  { id: '6', name: 'City', icon: '🏙️', color: '#FFE194' },
];

export const destinations = [
  {
    id: '1',
    name: 'Ooty',
    category: 'Hill Station',
    image: 'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=500',
    images: [
      'https://images.unsplash.com/photo-1589308078059-be1415eab4c3?w=500',
      'https://images.unsplash.com/photo-1597135096739-1fd8641c5edb?w=500',
    ],
    description: 'Queen of Hill Stations with beautiful tea gardens and colonial charm',
    location: 'Nilgiris District',
    district: 'Nilgiris',
    rating: 4.5,
    reviewCount: 1234,
    budget: '₹3,000 - ₹8,000',
    bestTime: 'April to June, September to November',
    overview: 'Ooty, also known as Udhagamandalam, is a beautiful hill station in the Nilgiri Hills. Famous for its tea plantations, botanical gardens, and pleasant climate throughout the year.',
    coordinates: { lat: 11.4064, lng: 76.6932 },
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Kodaikanal',
    category: 'Hill Station',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500',
    images: [
      'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500',
    ],
    description: 'Princess of Hill Stations with serene lakes and lush forests',
    location: 'Dindigul District',
    district: 'Dindigul',
    rating: 4.4,
    reviewCount: 987,
    budget: '₹2,500 - ₹7,000',
    bestTime: 'April to June, September to October',
    overview: 'Kodaikanal is a charming hill station known for its star-shaped lake, scenic viewpoints, and peaceful atmosphere.',
    coordinates: { lat: 10.2381, lng: 77.4892 },
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Rameswaram',
    category: 'Temple',
    image: 'https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=500',
    images: [
      'https://images.unsplash.com/photo-1587135941948-670b381f08ce?w=500',
    ],
    description: 'Sacred island town with magnificent temples and pristine beaches',
    location: 'Ramanathapuram District',
    district: 'Ramanathapuram',
    rating: 4.6,
    reviewCount: 1567,
    budget: '₹2,000 - ₹5,000',
    bestTime: 'October to March',
    overview: 'Rameswaram is a sacred pilgrimage destination featuring the famous Ramanathaswamy Temple.',
    coordinates: { lat: 9.2876, lng: 79.3129 },
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Madurai',
    category: 'Heritage',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500',
    images: [
      'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=500',
    ],
    description: 'Ancient city of temples and rich cultural heritage',
    location: 'Madurai District',
    district: 'Madurai',
    rating: 4.3,
    reviewCount: 2134,
    budget: '₹1,500 - ₹4,000',
    bestTime: 'October to March',
    overview: 'Madurai is famous for the magnificent Meenakshi Amman Temple, a stunning example of Dravidian architecture.',
    coordinates: { lat: 9.9252, lng: 78.1198 },
    isFeatured: true,
  },
];

export const featuredDestinations = destinations.filter(d => d.isFeatured);